version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4100:4100"
    restart: always
    networks:
      - my_network

networks:
  my_network:
    external: true
